package com.sagi.logic;
// Generated 03-feb-2014 12:00:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Files generated by hbm2java
 */
public class Files  implements java.io.Serializable {


     private String fileId;
     private Date fileStartDate;
     private String fileFiledNumber;
     private Date fileFiledDate;
     private Set<Processes> processeses = new HashSet<Processes>(0);
     private Set<Employees> employeeses = new HashSet<Employees>(0);
     private Set<Users> userses = new HashSet<Users>(0);

    public Files() {
    }

	
    public Files(String fileId, Date fileStartDate, String fileFiledNumber, Date fileFiledDate) {
        this.fileId = fileId;
        this.fileStartDate = fileStartDate;
        this.fileFiledNumber = fileFiledNumber;
        this.fileFiledDate = fileFiledDate;
    }
    public Files(String fileId, Date fileStartDate, String fileFiledNumber, Date fileFiledDate, Set<Processes> processeses, Set<Employees> employeeses, Set<Users> userses) {
       this.fileId = fileId;
       this.fileStartDate = fileStartDate;
       this.fileFiledNumber = fileFiledNumber;
       this.fileFiledDate = fileFiledDate;
       this.processeses = processeses;
       this.employeeses = employeeses;
       this.userses = userses;
    }
   
    public String getFileId() {
        return this.fileId;
    }
    
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }
    public Date getFileStartDate() {
        return this.fileStartDate;
    }
    
    public void setFileStartDate(Date fileStartDate) {
        this.fileStartDate = fileStartDate;
    }
    public String getFileFiledNumber() {
        return this.fileFiledNumber;
    }
    
    public void setFileFiledNumber(String fileFiledNumber) {
        this.fileFiledNumber = fileFiledNumber;
    }
    public Date getFileFiledDate() {
        return this.fileFiledDate;
    }
    
    public void setFileFiledDate(Date fileFiledDate) {
        this.fileFiledDate = fileFiledDate;
    }
    public Set<Processes> getProcesseses() {
        return this.processeses;
    }
    
    public void setProcesseses(Set<Processes> processeses) {
        this.processeses = processeses;
    }
    public Set<Employees> getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set<Employees> employeeses) {
        this.employeeses = employeeses;
    }
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


