package com.sagi.logic;
// Generated 03-feb-2014 12:00:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * HydricZone generated by hbm2java
 */
public class HydricZone  implements java.io.Serializable {


     private int hydricZoneId;
     private HydricZone hydricZone;
     private String hydricZoneName;
     private String hydricType;
     private Set<Locations> locationses = new HashSet<Locations>(0);
     private Set<HydricZone> hydricZones = new HashSet<HydricZone>(0);
     private Set<Source> sources = new HashSet<Source>(0);

    public HydricZone() {
    }

	
    public HydricZone(int hydricZoneId, String hydricZoneName, String hydricType) {
        this.hydricZoneId = hydricZoneId;
        this.hydricZoneName = hydricZoneName;
        this.hydricType = hydricType;
    }
    public HydricZone(int hydricZoneId, HydricZone hydricZone, String hydricZoneName, String hydricType, Set<Locations> locationses, Set<HydricZone> hydricZones, Set<Source> sources) {
       this.hydricZoneId = hydricZoneId;
       this.hydricZone = hydricZone;
       this.hydricZoneName = hydricZoneName;
       this.hydricType = hydricType;
       this.locationses = locationses;
       this.hydricZones = hydricZones;
       this.sources = sources;
    }
   
    public int getHydricZoneId() {
        return this.hydricZoneId;
    }
    
    public void setHydricZoneId(int hydricZoneId) {
        this.hydricZoneId = hydricZoneId;
    }
    public HydricZone getHydricZone() {
        return this.hydricZone;
    }
    
    public void setHydricZone(HydricZone hydricZone) {
        this.hydricZone = hydricZone;
    }
    public String getHydricZoneName() {
        return this.hydricZoneName;
    }
    
    public void setHydricZoneName(String hydricZoneName) {
        this.hydricZoneName = hydricZoneName;
    }
    public String getHydricType() {
        return this.hydricType;
    }
    
    public void setHydricType(String hydricType) {
        this.hydricType = hydricType;
    }
    public Set<Locations> getLocationses() {
        return this.locationses;
    }
    
    public void setLocationses(Set<Locations> locationses) {
        this.locationses = locationses;
    }
    public Set<HydricZone> getHydricZones() {
        return this.hydricZones;
    }
    
    public void setHydricZones(Set<HydricZone> hydricZones) {
        this.hydricZones = hydricZones;
    }
    public Set<Source> getSources() {
        return this.sources;
    }
    
    public void setSources(Set<Source> sources) {
        this.sources = sources;
    }




}


