package com.sagi.logic;
// Generated 11-dic-2013 13:19:53 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Jobs generated by hbm2java
 */
public class Jobs  implements java.io.Serializable {


     private int jobId;
     private String jobTitle;
     private Set<Employees> employeeses = new HashSet<Employees>(0);
     private Set<JobHistory> jobHistories = new HashSet<JobHistory>(0);

    public Jobs() {
    }

	
    public Jobs(int jobId, String jobTitle) {
        this.jobId = jobId;
        this.jobTitle = jobTitle;
    }
    public Jobs(int jobId, String jobTitle, Set<Employees> employeeses, Set<JobHistory> jobHistories) {
       this.jobId = jobId;
       this.jobTitle = jobTitle;
       this.employeeses = employeeses;
       this.jobHistories = jobHistories;
    }
   
    public int getJobId() {
        return this.jobId;
    }
    
    public void setJobId(int jobId) {
        this.jobId = jobId;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public Set<Employees> getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set<Employees> employeeses) {
        this.employeeses = employeeses;
    }
    public Set<JobHistory> getJobHistories() {
        return this.jobHistories;
    }
    
    public void setJobHistories(Set<JobHistory> jobHistories) {
        this.jobHistories = jobHistories;
    }




}


