package com.sagi.logic;
// Generated 03-feb-2014 12:00:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Locations generated by hbm2java
 */
public class Locations  implements java.io.Serializable {


     private int locationId;
     private Locations locations;
     private String locationType;
     private String locationName;
     private Set<HydricZone> hydricZones = new HashSet<HydricZone>(0);
     private Set<Locations> locationses = new HashSet<Locations>(0);
     private Set<Lands> landses = new HashSet<Lands>(0);

    public Locations() {
    }

	
    public Locations(int locationId, String locationType, String locationName) {
        this.locationId = locationId;
        this.locationType = locationType;
        this.locationName = locationName;
    }
    public Locations(int locationId, Locations locations, String locationType, String locationName, Set<HydricZone> hydricZones, Set<Locations> locationses, Set<Lands> landses) {
       this.locationId = locationId;
       this.locations = locations;
       this.locationType = locationType;
       this.locationName = locationName;
       this.hydricZones = hydricZones;
       this.locationses = locationses;
       this.landses = landses;
    }
   
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }
    public Locations getLocations() {
        return this.locations;
    }
    
    public void setLocations(Locations locations) {
        this.locations = locations;
    }
    public String getLocationType() {
        return this.locationType;
    }
    
    public void setLocationType(String locationType) {
        this.locationType = locationType;
    }
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }
    public Set<HydricZone> getHydricZones() {
        return this.hydricZones;
    }
    
    public void setHydricZones(Set<HydricZone> hydricZones) {
        this.hydricZones = hydricZones;
    }
    public Set<Locations> getLocationses() {
        return this.locationses;
    }
    
    public void setLocationses(Set<Locations> locationses) {
        this.locationses = locationses;
    }
    public Set<Lands> getLandses() {
        return this.landses;
    }
    
    public void setLandses(Set<Lands> landses) {
        this.landses = landses;
    }




}


