package com.sagi.logic;
// Generated 03-feb-2014 12:00:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Notices generated by hbm2java
 */
public class Notices  implements java.io.Serializable {


     private int noticeId;
     private Employees employeesByEmpIdElaborateNotice;
     private Employees employeesByEmpIdAuthorizeNotice;
     private Processes processes;
     private Date noticeCreationDate;
     private Date noticeVisitDate;
     private Date noticeVisitTime;
     private Boolean statusNotice;

    public Notices() {
    }

	
    public Notices(int noticeId, Processes processes, Date noticeCreationDate, Date noticeVisitDate, Date noticeVisitTime) {
        this.noticeId = noticeId;
        this.processes = processes;
        this.noticeCreationDate = noticeCreationDate;
        this.noticeVisitDate = noticeVisitDate;
        this.noticeVisitTime = noticeVisitTime;
    }
    public Notices(int noticeId, Employees employeesByEmpIdElaborateNotice, Employees employeesByEmpIdAuthorizeNotice, Processes processes, Date noticeCreationDate, Date noticeVisitDate, Date noticeVisitTime, Boolean statusNotice) {
       this.noticeId = noticeId;
       this.employeesByEmpIdElaborateNotice = employeesByEmpIdElaborateNotice;
       this.employeesByEmpIdAuthorizeNotice = employeesByEmpIdAuthorizeNotice;
       this.processes = processes;
       this.noticeCreationDate = noticeCreationDate;
       this.noticeVisitDate = noticeVisitDate;
       this.noticeVisitTime = noticeVisitTime;
       this.statusNotice = statusNotice;
    }
   
    public int getNoticeId() {
        return this.noticeId;
    }
    
    public void setNoticeId(int noticeId) {
        this.noticeId = noticeId;
    }
    public Employees getEmployeesByEmpIdElaborateNotice() {
        return this.employeesByEmpIdElaborateNotice;
    }
    
    public void setEmployeesByEmpIdElaborateNotice(Employees employeesByEmpIdElaborateNotice) {
        this.employeesByEmpIdElaborateNotice = employeesByEmpIdElaborateNotice;
    }
    public Employees getEmployeesByEmpIdAuthorizeNotice() {
        return this.employeesByEmpIdAuthorizeNotice;
    }
    
    public void setEmployeesByEmpIdAuthorizeNotice(Employees employeesByEmpIdAuthorizeNotice) {
        this.employeesByEmpIdAuthorizeNotice = employeesByEmpIdAuthorizeNotice;
    }
    public Processes getProcesses() {
        return this.processes;
    }
    
    public void setProcesses(Processes processes) {
        this.processes = processes;
    }
    public Date getNoticeCreationDate() {
        return this.noticeCreationDate;
    }
    
    public void setNoticeCreationDate(Date noticeCreationDate) {
        this.noticeCreationDate = noticeCreationDate;
    }
    public Date getNoticeVisitDate() {
        return this.noticeVisitDate;
    }
    
    public void setNoticeVisitDate(Date noticeVisitDate) {
        this.noticeVisitDate = noticeVisitDate;
    }
    public Date getNoticeVisitTime() {
        return this.noticeVisitTime;
    }
    
    public void setNoticeVisitTime(Date noticeVisitTime) {
        this.noticeVisitTime = noticeVisitTime;
    }
    public Boolean getStatusNotice() {
        return this.statusNotice;
    }
    
    public void setStatusNotice(Boolean statusNotice) {
        this.statusNotice = statusNotice;
    }




}


