package com.sagi.logic;
// Generated 03-feb-2014 12:00:45 by Hibernate Tools 3.2.1.GA



/**
 * Photography generated by hbm2java
 */
public class Photography  implements java.io.Serializable {


     private int photoId;
     private TechnicalConcept technicalConcept;
     private byte[] photo;
     private String photoDescription;

    public Photography() {
    }

    public Photography(int photoId, TechnicalConcept technicalConcept, byte[] photo, String photoDescription) {
       this.photoId = photoId;
       this.technicalConcept = technicalConcept;
       this.photo = photo;
       this.photoDescription = photoDescription;
    }
   
    public int getPhotoId() {
        return this.photoId;
    }
    
    public void setPhotoId(int photoId) {
        this.photoId = photoId;
    }
    public TechnicalConcept getTechnicalConcept() {
        return this.technicalConcept;
    }
    
    public void setTechnicalConcept(TechnicalConcept technicalConcept) {
        this.technicalConcept = technicalConcept;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public String getPhotoDescription() {
        return this.photoDescription;
    }
    
    public void setPhotoDescription(String photoDescription) {
        this.photoDescription = photoDescription;
    }




}


