package com.sagi.logic;
// Generated 03-feb-2014 12:00:45 by Hibernate Tools 3.2.1.GA



/**
 * Points generated by hbm2java
 */
public class Points  implements java.io.Serializable {


     private int pointId;
     private Source source;
     private Processes processes;
     private int latitudeGrade;
     private int latitudeMinute;
     private int latitudeSecond;
     private int longitudeGrade;
     private int longitudeMinute;
     private int longitudeSecond;
     private long caudal;
     private String downloadType;
     private Byte downloadFrecuency;
     private Long downloadTime;
     private String gaugingSystem;

    public Points() {
    }

	
    public Points(int pointId, Source source, Processes processes, int latitudeGrade, int latitudeMinute, int latitudeSecond, int longitudeGrade, int longitudeMinute, int longitudeSecond, long caudal) {
        this.pointId = pointId;
        this.source = source;
        this.processes = processes;
        this.latitudeGrade = latitudeGrade;
        this.latitudeMinute = latitudeMinute;
        this.latitudeSecond = latitudeSecond;
        this.longitudeGrade = longitudeGrade;
        this.longitudeMinute = longitudeMinute;
        this.longitudeSecond = longitudeSecond;
        this.caudal = caudal;
    }
    public Points(int pointId, Source source, Processes processes, int latitudeGrade, int latitudeMinute, int latitudeSecond, int longitudeGrade, int longitudeMinute, int longitudeSecond, long caudal, String downloadType, Byte downloadFrecuency, Long downloadTime, String gaugingSystem) {
       this.pointId = pointId;
       this.source = source;
       this.processes = processes;
       this.latitudeGrade = latitudeGrade;
       this.latitudeMinute = latitudeMinute;
       this.latitudeSecond = latitudeSecond;
       this.longitudeGrade = longitudeGrade;
       this.longitudeMinute = longitudeMinute;
       this.longitudeSecond = longitudeSecond;
       this.caudal = caudal;
       this.downloadType = downloadType;
       this.downloadFrecuency = downloadFrecuency;
       this.downloadTime = downloadTime;
       this.gaugingSystem = gaugingSystem;
    }
   
    public int getPointId() {
        return this.pointId;
    }
    
    public void setPointId(int pointId) {
        this.pointId = pointId;
    }
    public Source getSource() {
        return this.source;
    }
    
    public void setSource(Source source) {
        this.source = source;
    }
    public Processes getProcesses() {
        return this.processes;
    }
    
    public void setProcesses(Processes processes) {
        this.processes = processes;
    }
    public int getLatitudeGrade() {
        return this.latitudeGrade;
    }
    
    public void setLatitudeGrade(int latitudeGrade) {
        this.latitudeGrade = latitudeGrade;
    }
    public int getLatitudeMinute() {
        return this.latitudeMinute;
    }
    
    public void setLatitudeMinute(int latitudeMinute) {
        this.latitudeMinute = latitudeMinute;
    }
    public int getLatitudeSecond() {
        return this.latitudeSecond;
    }
    
    public void setLatitudeSecond(int latitudeSecond) {
        this.latitudeSecond = latitudeSecond;
    }
    public int getLongitudeGrade() {
        return this.longitudeGrade;
    }
    
    public void setLongitudeGrade(int longitudeGrade) {
        this.longitudeGrade = longitudeGrade;
    }
    public int getLongitudeMinute() {
        return this.longitudeMinute;
    }
    
    public void setLongitudeMinute(int longitudeMinute) {
        this.longitudeMinute = longitudeMinute;
    }
    public int getLongitudeSecond() {
        return this.longitudeSecond;
    }
    
    public void setLongitudeSecond(int longitudeSecond) {
        this.longitudeSecond = longitudeSecond;
    }
    public long getCaudal() {
        return this.caudal;
    }
    
    public void setCaudal(long caudal) {
        this.caudal = caudal;
    }
    public String getDownloadType() {
        return this.downloadType;
    }
    
    public void setDownloadType(String downloadType) {
        this.downloadType = downloadType;
    }
    public Byte getDownloadFrecuency() {
        return this.downloadFrecuency;
    }
    
    public void setDownloadFrecuency(Byte downloadFrecuency) {
        this.downloadFrecuency = downloadFrecuency;
    }
    public Long getDownloadTime() {
        return this.downloadTime;
    }
    
    public void setDownloadTime(Long downloadTime) {
        this.downloadTime = downloadTime;
    }
    public String getGaugingSystem() {
        return this.gaugingSystem;
    }
    
    public void setGaugingSystem(String gaugingSystem) {
        this.gaugingSystem = gaugingSystem;
    }




}


