package com.sagi.logic;
// Generated 03-feb-2014 12:00:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Processes generated by hbm2java
 */
public class Processes  implements java.io.Serializable {


     private String processId;
     private Employees employees;
     private Lands lands;
     private Files files;
     private String processType;
     private Date processStartDate;
     private int processTime;
     private float processInvestmentCost;
     private float processOperationCost;
     private Set<AutoStart> autoStarts = new HashSet<AutoStart>(0);
     private Set<Points> pointses = new HashSet<Points>(0);
     private Set<Resolution> resolutions = new HashSet<Resolution>(0);
     private Set<Notices> noticeses = new HashSet<Notices>(0);
     private Set<UseDescription> useDescriptions = new HashSet<UseDescription>(0);
     private Set<TechnicalConcept> technicalConcepts = new HashSet<TechnicalConcept>(0);
     private Set<AutoRequirement> autoRequirements = new HashSet<AutoRequirement>(0);

    public Processes() {
    }

	
    public Processes(String processId, Employees employees, Lands lands, Files files, String processType, Date processStartDate, int processTime, float processInvestmentCost, float processOperationCost) {
        this.processId = processId;
        this.employees = employees;
        this.lands = lands;
        this.files = files;
        this.processType = processType;
        this.processStartDate = processStartDate;
        this.processTime = processTime;
        this.processInvestmentCost = processInvestmentCost;
        this.processOperationCost = processOperationCost;
    }
    public Processes(String processId, Employees employees, Lands lands, Files files, String processType, Date processStartDate, int processTime, float processInvestmentCost, float processOperationCost, Set<AutoStart> autoStarts, Set<Points> pointses, Set<Resolution> resolutions, Set<Notices> noticeses, Set<UseDescription> useDescriptions, Set<TechnicalConcept> technicalConcepts, Set<AutoRequirement> autoRequirements) {
       this.processId = processId;
       this.employees = employees;
       this.lands = lands;
       this.files = files;
       this.processType = processType;
       this.processStartDate = processStartDate;
       this.processTime = processTime;
       this.processInvestmentCost = processInvestmentCost;
       this.processOperationCost = processOperationCost;
       this.autoStarts = autoStarts;
       this.pointses = pointses;
       this.resolutions = resolutions;
       this.noticeses = noticeses;
       this.useDescriptions = useDescriptions;
       this.technicalConcepts = technicalConcepts;
       this.autoRequirements = autoRequirements;
    }
   
    public String getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(String processId) {
        this.processId = processId;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Lands getLands() {
        return this.lands;
    }
    
    public void setLands(Lands lands) {
        this.lands = lands;
    }
    public Files getFiles() {
        return this.files;
    }
    
    public void setFiles(Files files) {
        this.files = files;
    }
    public String getProcessType() {
        return this.processType;
    }
    
    public void setProcessType(String processType) {
        this.processType = processType;
    }
    public Date getProcessStartDate() {
        return this.processStartDate;
    }
    
    public void setProcessStartDate(Date processStartDate) {
        this.processStartDate = processStartDate;
    }
    public int getProcessTime() {
        return this.processTime;
    }
    
    public void setProcessTime(int processTime) {
        this.processTime = processTime;
    }
    public float getProcessInvestmentCost() {
        return this.processInvestmentCost;
    }
    
    public void setProcessInvestmentCost(float processInvestmentCost) {
        this.processInvestmentCost = processInvestmentCost;
    }
    public float getProcessOperationCost() {
        return this.processOperationCost;
    }
    
    public void setProcessOperationCost(float processOperationCost) {
        this.processOperationCost = processOperationCost;
    }
    public Set<AutoStart> getAutoStarts() {
        return this.autoStarts;
    }
    
    public void setAutoStarts(Set<AutoStart> autoStarts) {
        this.autoStarts = autoStarts;
    }
    public Set<Points> getPointses() {
        return this.pointses;
    }
    
    public void setPointses(Set<Points> pointses) {
        this.pointses = pointses;
    }
    public Set<Resolution> getResolutions() {
        return this.resolutions;
    }
    
    public void setResolutions(Set<Resolution> resolutions) {
        this.resolutions = resolutions;
    }
    public Set<Notices> getNoticeses() {
        return this.noticeses;
    }
    
    public void setNoticeses(Set<Notices> noticeses) {
        this.noticeses = noticeses;
    }
    public Set<UseDescription> getUseDescriptions() {
        return this.useDescriptions;
    }
    
    public void setUseDescriptions(Set<UseDescription> useDescriptions) {
        this.useDescriptions = useDescriptions;
    }
    public Set<TechnicalConcept> getTechnicalConcepts() {
        return this.technicalConcepts;
    }
    
    public void setTechnicalConcepts(Set<TechnicalConcept> technicalConcepts) {
        this.technicalConcepts = technicalConcepts;
    }
    public Set<AutoRequirement> getAutoRequirements() {
        return this.autoRequirements;
    }
    
    public void setAutoRequirements(Set<AutoRequirement> autoRequirements) {
        this.autoRequirements = autoRequirements;
    }




}


