package com.sagi.logic;
// Generated 03-feb-2014 12:00:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Resolution generated by hbm2java
 */
public class Resolution  implements java.io.Serializable {


     private int resolutionId;
     private Employees employeesByEmpIdElaborateResolution;
     private Employees employeesByEmpIdAuthorizeResolution;
     private Processes processes;
     private Date resolutionEndDate;
     private Date resolutionCreationDate;
     private String resolutionDescription;
     private Boolean statusResolution;

    public Resolution() {
    }

	
    public Resolution(int resolutionId, Processes processes, Date resolutionEndDate, Date resolutionCreationDate, String resolutionDescription) {
        this.resolutionId = resolutionId;
        this.processes = processes;
        this.resolutionEndDate = resolutionEndDate;
        this.resolutionCreationDate = resolutionCreationDate;
        this.resolutionDescription = resolutionDescription;
    }
    public Resolution(int resolutionId, Employees employeesByEmpIdElaborateResolution, Employees employeesByEmpIdAuthorizeResolution, Processes processes, Date resolutionEndDate, Date resolutionCreationDate, String resolutionDescription, Boolean statusResolution) {
       this.resolutionId = resolutionId;
       this.employeesByEmpIdElaborateResolution = employeesByEmpIdElaborateResolution;
       this.employeesByEmpIdAuthorizeResolution = employeesByEmpIdAuthorizeResolution;
       this.processes = processes;
       this.resolutionEndDate = resolutionEndDate;
       this.resolutionCreationDate = resolutionCreationDate;
       this.resolutionDescription = resolutionDescription;
       this.statusResolution = statusResolution;
    }
   
    public int getResolutionId() {
        return this.resolutionId;
    }
    
    public void setResolutionId(int resolutionId) {
        this.resolutionId = resolutionId;
    }
    public Employees getEmployeesByEmpIdElaborateResolution() {
        return this.employeesByEmpIdElaborateResolution;
    }
    
    public void setEmployeesByEmpIdElaborateResolution(Employees employeesByEmpIdElaborateResolution) {
        this.employeesByEmpIdElaborateResolution = employeesByEmpIdElaborateResolution;
    }
    public Employees getEmployeesByEmpIdAuthorizeResolution() {
        return this.employeesByEmpIdAuthorizeResolution;
    }
    
    public void setEmployeesByEmpIdAuthorizeResolution(Employees employeesByEmpIdAuthorizeResolution) {
        this.employeesByEmpIdAuthorizeResolution = employeesByEmpIdAuthorizeResolution;
    }
    public Processes getProcesses() {
        return this.processes;
    }
    
    public void setProcesses(Processes processes) {
        this.processes = processes;
    }
    public Date getResolutionEndDate() {
        return this.resolutionEndDate;
    }
    
    public void setResolutionEndDate(Date resolutionEndDate) {
        this.resolutionEndDate = resolutionEndDate;
    }
    public Date getResolutionCreationDate() {
        return this.resolutionCreationDate;
    }
    
    public void setResolutionCreationDate(Date resolutionCreationDate) {
        this.resolutionCreationDate = resolutionCreationDate;
    }
    public String getResolutionDescription() {
        return this.resolutionDescription;
    }
    
    public void setResolutionDescription(String resolutionDescription) {
        this.resolutionDescription = resolutionDescription;
    }
    public Boolean getStatusResolution() {
        return this.statusResolution;
    }
    
    public void setStatusResolution(Boolean statusResolution) {
        this.statusResolution = statusResolution;
    }




}


