package com.sagi.logic;
// Generated 03-feb-2014 12:00:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Source generated by hbm2java
 */
public class Source  implements java.io.Serializable {


     private int sourceId;
     private String sourceName;
     private String sourceType;
     private Long suspendedSolids;
     private Long dbo5;
     private Long dqo;
     private Long sourceCaudal;
     private String SD;
     private Set<HydricZone> hydricZones = new HashSet<HydricZone>(0);
     private Set<Points> pointses = new HashSet<Points>(0);

    public Source() {
    }

	
    public Source(int sourceId, String sourceName, String sourceType, String SD) {
        this.sourceId = sourceId;
        this.sourceName = sourceName;
        this.sourceType = sourceType;
        this.SD = SD;
    }
    public Source(int sourceId, String sourceName, String sourceType, Long suspendedSolids, Long dbo5, Long dqo, Long sourceCaudal, String SD, Set<HydricZone> hydricZones, Set<Points> pointses) {
       this.sourceId = sourceId;
       this.sourceName = sourceName;
       this.sourceType = sourceType;
       this.suspendedSolids = suspendedSolids;
       this.dbo5 = dbo5;
       this.dqo = dqo;
       this.sourceCaudal = sourceCaudal;
       this.SD = SD;
       this.hydricZones = hydricZones;
       this.pointses = pointses;
    }
   
    public int getSourceId() {
        return this.sourceId;
    }
    
    public void setSourceId(int sourceId) {
        this.sourceId = sourceId;
    }
    public String getSourceName() {
        return this.sourceName;
    }
    
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }
    public String getSourceType() {
        return this.sourceType;
    }
    
    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }
    public Long getSuspendedSolids() {
        return this.suspendedSolids;
    }
    
    public void setSuspendedSolids(Long suspendedSolids) {
        this.suspendedSolids = suspendedSolids;
    }
    public Long getDbo5() {
        return this.dbo5;
    }
    
    public void setDbo5(Long dbo5) {
        this.dbo5 = dbo5;
    }
    public Long getDqo() {
        return this.dqo;
    }
    
    public void setDqo(Long dqo) {
        this.dqo = dqo;
    }
    public Long getSourceCaudal() {
        return this.sourceCaudal;
    }
    
    public void setSourceCaudal(Long sourceCaudal) {
        this.sourceCaudal = sourceCaudal;
    }
    public String getSD() {
        return this.SD;
    }
    
    public void setSD(String SD) {
        this.SD = SD;
    }
    public Set<HydricZone> getHydricZones() {
        return this.hydricZones;
    }
    
    public void setHydricZones(Set<HydricZone> hydricZones) {
        this.hydricZones = hydricZones;
    }
    public Set<Points> getPointses() {
        return this.pointses;
    }
    
    public void setPointses(Set<Points> pointses) {
        this.pointses = pointses;
    }




}


