package com.sagi.logic;
// Generated 11-dic-2013 13:19:53 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Subdirectorates generated by hbm2java
 */
public class Subdirectorates  implements java.io.Serializable {


     private int subdirectorateId;
     private Employees employees;
     private String subdirectorateName;
     private Set<Employees> employeeses = new HashSet<Employees>(0);
     private Set<JobHistory> jobHistories = new HashSet<JobHistory>(0);

    public Subdirectorates() {
    }

	
    public Subdirectorates(int subdirectorateId, String subdirectorateName) {
        this.subdirectorateId = subdirectorateId;
        this.subdirectorateName = subdirectorateName;
    }
    public Subdirectorates(int subdirectorateId, Employees employees, String subdirectorateName, Set<Employees> employeeses, Set<JobHistory> jobHistories) {
       this.subdirectorateId = subdirectorateId;
       this.employees = employees;
       this.subdirectorateName = subdirectorateName;
       this.employeeses = employeeses;
       this.jobHistories = jobHistories;
    }
   
    public int getSubdirectorateId() {
        return this.subdirectorateId;
    }
    
    public void setSubdirectorateId(int subdirectorateId) {
        this.subdirectorateId = subdirectorateId;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getSubdirectorateName() {
        return this.subdirectorateName;
    }
    
    public void setSubdirectorateName(String subdirectorateName) {
        this.subdirectorateName = subdirectorateName;
    }
    public Set<Employees> getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set<Employees> employeeses) {
        this.employeeses = employeeses;
    }
    public Set<JobHistory> getJobHistories() {
        return this.jobHistories;
    }
    
    public void setJobHistories(Set<JobHistory> jobHistories) {
        this.jobHistories = jobHistories;
    }




}


