package com.sagi.logic;
// Generated 03-feb-2014 12:00:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TechnicalConcept generated by hbm2java
 */
public class TechnicalConcept  implements java.io.Serializable {


     private int conceptId;
     private Employees employeesByEmpIdAutorizeConcept;
     private Employees employeesByEmpIdElaborateConcept;
     private Processes processes;
     private boolean conceptOposition;
     private boolean conceptUserCompensation;
     private long conceptUserCaudal;
     private boolean conceptUserAnnexe;
     private boolean conceptUserRate;
     private String conceptUserDescription;
     private boolean statusTechnicalConcept;
     private Set<Photography> photographies = new HashSet<Photography>(0);

    public TechnicalConcept() {
    }

	
    public TechnicalConcept(int conceptId, Processes processes, boolean conceptOposition, boolean conceptUserCompensation, long conceptUserCaudal, boolean conceptUserAnnexe, boolean conceptUserRate, String conceptUserDescription, boolean statusTechnicalConcept) {
        this.conceptId = conceptId;
        this.processes = processes;
        this.conceptOposition = conceptOposition;
        this.conceptUserCompensation = conceptUserCompensation;
        this.conceptUserCaudal = conceptUserCaudal;
        this.conceptUserAnnexe = conceptUserAnnexe;
        this.conceptUserRate = conceptUserRate;
        this.conceptUserDescription = conceptUserDescription;
        this.statusTechnicalConcept = statusTechnicalConcept;
    }
    public TechnicalConcept(int conceptId, Employees employeesByEmpIdAutorizeConcept, Employees employeesByEmpIdElaborateConcept, Processes processes, boolean conceptOposition, boolean conceptUserCompensation, long conceptUserCaudal, boolean conceptUserAnnexe, boolean conceptUserRate, String conceptUserDescription, boolean statusTechnicalConcept, Set<Photography> photographies) {
       this.conceptId = conceptId;
       this.employeesByEmpIdAutorizeConcept = employeesByEmpIdAutorizeConcept;
       this.employeesByEmpIdElaborateConcept = employeesByEmpIdElaborateConcept;
       this.processes = processes;
       this.conceptOposition = conceptOposition;
       this.conceptUserCompensation = conceptUserCompensation;
       this.conceptUserCaudal = conceptUserCaudal;
       this.conceptUserAnnexe = conceptUserAnnexe;
       this.conceptUserRate = conceptUserRate;
       this.conceptUserDescription = conceptUserDescription;
       this.statusTechnicalConcept = statusTechnicalConcept;
       this.photographies = photographies;
    }
   
    public int getConceptId() {
        return this.conceptId;
    }
    
    public void setConceptId(int conceptId) {
        this.conceptId = conceptId;
    }
    public Employees getEmployeesByEmpIdAutorizeConcept() {
        return this.employeesByEmpIdAutorizeConcept;
    }
    
    public void setEmployeesByEmpIdAutorizeConcept(Employees employeesByEmpIdAutorizeConcept) {
        this.employeesByEmpIdAutorizeConcept = employeesByEmpIdAutorizeConcept;
    }
    public Employees getEmployeesByEmpIdElaborateConcept() {
        return this.employeesByEmpIdElaborateConcept;
    }
    
    public void setEmployeesByEmpIdElaborateConcept(Employees employeesByEmpIdElaborateConcept) {
        this.employeesByEmpIdElaborateConcept = employeesByEmpIdElaborateConcept;
    }
    public Processes getProcesses() {
        return this.processes;
    }
    
    public void setProcesses(Processes processes) {
        this.processes = processes;
    }
    public boolean isConceptOposition() {
        return this.conceptOposition;
    }
    
    public void setConceptOposition(boolean conceptOposition) {
        this.conceptOposition = conceptOposition;
    }
    public boolean isConceptUserCompensation() {
        return this.conceptUserCompensation;
    }
    
    public void setConceptUserCompensation(boolean conceptUserCompensation) {
        this.conceptUserCompensation = conceptUserCompensation;
    }
    public long getConceptUserCaudal() {
        return this.conceptUserCaudal;
    }
    
    public void setConceptUserCaudal(long conceptUserCaudal) {
        this.conceptUserCaudal = conceptUserCaudal;
    }
    public boolean isConceptUserAnnexe() {
        return this.conceptUserAnnexe;
    }
    
    public void setConceptUserAnnexe(boolean conceptUserAnnexe) {
        this.conceptUserAnnexe = conceptUserAnnexe;
    }
    public boolean isConceptUserRate() {
        return this.conceptUserRate;
    }
    
    public void setConceptUserRate(boolean conceptUserRate) {
        this.conceptUserRate = conceptUserRate;
    }
    public String getConceptUserDescription() {
        return this.conceptUserDescription;
    }
    
    public void setConceptUserDescription(String conceptUserDescription) {
        this.conceptUserDescription = conceptUserDescription;
    }
    public boolean isStatusTechnicalConcept() {
        return this.statusTechnicalConcept;
    }
    
    public void setStatusTechnicalConcept(boolean statusTechnicalConcept) {
        this.statusTechnicalConcept = statusTechnicalConcept;
    }
    public Set<Photography> getPhotographies() {
        return this.photographies;
    }
    
    public void setPhotographies(Set<Photography> photographies) {
        this.photographies = photographies;
    }




}


