package com.sagi.logic;
// Generated 03-feb-2014 12:00:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UseDescription generated by hbm2java
 */
public class UseDescription  implements java.io.Serializable {


     private int useDescriptionId;
     private Processes processes;
     private Integer userNumber;
     private Integer familiesNumber;
     private Integer permanentUserNumber;
     private Integer transientUserNumber;
     private String animalType;
     private Integer animalNumber;
     private String cropType;
     private Long cropArea;
     private String cropIrrigationType;
     private String useDescription;
     private String treatmentSystem;
     private Set<Uses> useses = new HashSet<Uses>(0);

    public UseDescription() {
    }

	
    public UseDescription(int useDescriptionId, Processes processes) {
        this.useDescriptionId = useDescriptionId;
        this.processes = processes;
    }
    public UseDescription(int useDescriptionId, Processes processes, Integer userNumber, Integer familiesNumber, Integer permanentUserNumber, Integer transientUserNumber, String animalType, Integer animalNumber, String cropType, Long cropArea, String cropIrrigationType, String useDescription, String treatmentSystem, Set<Uses> useses) {
       this.useDescriptionId = useDescriptionId;
       this.processes = processes;
       this.userNumber = userNumber;
       this.familiesNumber = familiesNumber;
       this.permanentUserNumber = permanentUserNumber;
       this.transientUserNumber = transientUserNumber;
       this.animalType = animalType;
       this.animalNumber = animalNumber;
       this.cropType = cropType;
       this.cropArea = cropArea;
       this.cropIrrigationType = cropIrrigationType;
       this.useDescription = useDescription;
       this.treatmentSystem = treatmentSystem;
       this.useses = useses;
    }
   
    public int getUseDescriptionId() {
        return this.useDescriptionId;
    }
    
    public void setUseDescriptionId(int useDescriptionId) {
        this.useDescriptionId = useDescriptionId;
    }
    public Processes getProcesses() {
        return this.processes;
    }
    
    public void setProcesses(Processes processes) {
        this.processes = processes;
    }
    public Integer getUserNumber() {
        return this.userNumber;
    }
    
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }
    public Integer getFamiliesNumber() {
        return this.familiesNumber;
    }
    
    public void setFamiliesNumber(Integer familiesNumber) {
        this.familiesNumber = familiesNumber;
    }
    public Integer getPermanentUserNumber() {
        return this.permanentUserNumber;
    }
    
    public void setPermanentUserNumber(Integer permanentUserNumber) {
        this.permanentUserNumber = permanentUserNumber;
    }
    public Integer getTransientUserNumber() {
        return this.transientUserNumber;
    }
    
    public void setTransientUserNumber(Integer transientUserNumber) {
        this.transientUserNumber = transientUserNumber;
    }
    public String getAnimalType() {
        return this.animalType;
    }
    
    public void setAnimalType(String animalType) {
        this.animalType = animalType;
    }
    public Integer getAnimalNumber() {
        return this.animalNumber;
    }
    
    public void setAnimalNumber(Integer animalNumber) {
        this.animalNumber = animalNumber;
    }
    public String getCropType() {
        return this.cropType;
    }
    
    public void setCropType(String cropType) {
        this.cropType = cropType;
    }
    public Long getCropArea() {
        return this.cropArea;
    }
    
    public void setCropArea(Long cropArea) {
        this.cropArea = cropArea;
    }
    public String getCropIrrigationType() {
        return this.cropIrrigationType;
    }
    
    public void setCropIrrigationType(String cropIrrigationType) {
        this.cropIrrigationType = cropIrrigationType;
    }
    public String getUseDescription() {
        return this.useDescription;
    }
    
    public void setUseDescription(String useDescription) {
        this.useDescription = useDescription;
    }
    public String getTreatmentSystem() {
        return this.treatmentSystem;
    }
    
    public void setTreatmentSystem(String treatmentSystem) {
        this.treatmentSystem = treatmentSystem;
    }
    public Set<Uses> getUseses() {
        return this.useses;
    }
    
    public void setUseses(Set<Uses> useses) {
        this.useses = useses;
    }




}


