package com.sagi.logic;
// Generated 03-feb-2014 12:00:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String userId;
     private Users usersByUserRepresentativeUserId;
     private Users usersByUserRepresntativeLawyerId;
     private String userType;
     private String userCharacteristic;
     private String tenancyType;
     private String firstName;
     private String lastName;
     private String streetAddress;
     private String city;
     private String phoneNumber;
     private String email;
     private String documentType;
     private String documentCity;
     private Set<Users> usersesForUserRepresentativeUserId = new HashSet<Users>(0);
     private Set<Files> fileses = new HashSet<Files>(0);
     private Set<Users> usersesForUserRepresntativeLawyerId = new HashSet<Users>(0);

    public Users() {
    }

	
    public Users(String userId, String userType, String tenancyType, String lastName, String streetAddress, String city, String phoneNumber, String documentType, String documentCity) {
        this.userId = userId;
        this.userType = userType;
        this.tenancyType = tenancyType;
        this.lastName = lastName;
        this.streetAddress = streetAddress;
        this.city = city;
        this.phoneNumber = phoneNumber;
        this.documentType = documentType;
        this.documentCity = documentCity;
    }
    public Users(String userId, Users usersByUserRepresentativeUserId, Users usersByUserRepresntativeLawyerId, String userType, String userCharacteristic, String tenancyType, String firstName, String lastName, String streetAddress, String city, String phoneNumber, String email, String documentType, String documentCity, Set<Users> usersesForUserRepresentativeUserId, Set<Files> fileses, Set<Users> usersesForUserRepresntativeLawyerId) {
       this.userId = userId;
       this.usersByUserRepresentativeUserId = usersByUserRepresentativeUserId;
       this.usersByUserRepresntativeLawyerId = usersByUserRepresntativeLawyerId;
       this.userType = userType;
       this.userCharacteristic = userCharacteristic;
       this.tenancyType = tenancyType;
       this.firstName = firstName;
       this.lastName = lastName;
       this.streetAddress = streetAddress;
       this.city = city;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.documentType = documentType;
       this.documentCity = documentCity;
       this.usersesForUserRepresentativeUserId = usersesForUserRepresentativeUserId;
       this.fileses = fileses;
       this.usersesForUserRepresntativeLawyerId = usersesForUserRepresntativeLawyerId;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Users getUsersByUserRepresentativeUserId() {
        return this.usersByUserRepresentativeUserId;
    }
    
    public void setUsersByUserRepresentativeUserId(Users usersByUserRepresentativeUserId) {
        this.usersByUserRepresentativeUserId = usersByUserRepresentativeUserId;
    }
    public Users getUsersByUserRepresntativeLawyerId() {
        return this.usersByUserRepresntativeLawyerId;
    }
    
    public void setUsersByUserRepresntativeLawyerId(Users usersByUserRepresntativeLawyerId) {
        this.usersByUserRepresntativeLawyerId = usersByUserRepresntativeLawyerId;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public String getUserCharacteristic() {
        return this.userCharacteristic;
    }
    
    public void setUserCharacteristic(String userCharacteristic) {
        this.userCharacteristic = userCharacteristic;
    }
    public String getTenancyType() {
        return this.tenancyType;
    }
    
    public void setTenancyType(String tenancyType) {
        this.tenancyType = tenancyType;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getStreetAddress() {
        return this.streetAddress;
    }
    
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }
    public String getDocumentCity() {
        return this.documentCity;
    }
    
    public void setDocumentCity(String documentCity) {
        this.documentCity = documentCity;
    }
    public Set<Users> getUsersesForUserRepresentativeUserId() {
        return this.usersesForUserRepresentativeUserId;
    }
    
    public void setUsersesForUserRepresentativeUserId(Set<Users> usersesForUserRepresentativeUserId) {
        this.usersesForUserRepresentativeUserId = usersesForUserRepresentativeUserId;
    }
    public Set<Files> getFileses() {
        return this.fileses;
    }
    
    public void setFileses(Set<Files> fileses) {
        this.fileses = fileses;
    }
    public Set<Users> getUsersesForUserRepresntativeLawyerId() {
        return this.usersesForUserRepresntativeLawyerId;
    }
    
    public void setUsersesForUserRepresntativeLawyerId(Set<Users> usersesForUserRepresntativeLawyerId) {
        this.usersesForUserRepresntativeLawyerId = usersesForUserRepresntativeLawyerId;
    }




}


